create table company
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_company primary key (id)
);

create table banned_domain
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_banned_domain primary key (id)
);

insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');

insert into banned_domain (name)
values ('banned.hu'),
       ('zxcv.com'),
       ('zzz.com');

create table contact
(
    id   bigint generated by default as identity,
    first_name varchar(200) not null,
    last_name varchar(200) not null,
    email varchar(200) not null,
    phone_number varchar(15),
    comment text not null,
    company_id bigint not null,
    status varchar(30) not null,
    created_date timestamp not null,
    last_modified_date timestamp not null,
    constraint pk_contact primary key (id),
    foreign key (company_id) references company(id)
);

create table app_user
{
    id   bigint generated by default as identity,
    email varchar(255) not null,
    password varchar(255) not null,
    constraint pk_app_user primary key (id)
}